### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by FuZeEclipse** [uakfdotb/uxpanel#3]
Fatal error: Call to a member function fetch_array() on a non-object in /home2/aura/public_html/panel/include/common.php on line 463

Tried logging in and got this.

**Comment by uakfdotb** [comment]
Have you created all of the necessary tables in the database (by running install.sql on the database)? The error is related to the locks table being missing.

In a future update I'm planning on switching everything over to PDO, but until then the error messages are rather vague.

Edit: also take a look at /check.php for a basic configuration / file check.

**Comment by uakfdotb** [comment]
Assuming this issue is resolved by creating the tables and following installation instructions in INSTALL file.
