### ISSUE TITLE
Errors in all the panel

### ISSUE THREAD

**Issue by carl0sra1n** [uakfdotb/uxpanel#8]
img 1:
![error1](https://f.cloud.github.com/assets/5181428/923604/491f38cc-ff4f-11e2-8ce9-c837e4fea0d8.png)

img 2:
![error2](https://f.cloud.github.com/assets/5181428/923609/730c465c-ff4f-11e2-8084-8566f6cedef5.png)

img 3:
![error3](https://f.cloud.github.com/assets/5181428/923613/8593f932-ff4f-11e2-88e6-827d3e54fa16.png)

My PHP Info:http://craftivo.com.ar/phpinfo2.php

**Comment by uakfdotb** [comment]
You need to enable PHP short tags; uxpanel uses these everywhere.

See http://stackoverflow.com/questions/2185320/how-to-enable-php-short-tags

**Comment by carl0sra1n** [comment]
Now it's working. Thanks.
